apiVersion: v1
kind: Service
metadata:
  name: {{ template "base.name" . }}
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 9091
      protocol: TCP
      targetPort: metrics
  selector:
    app: deployment
