language: go
GO111MODULE: on
go:
  - 1.13

git:
  quiet: true

services:
  - docker

install:
  - chmod +x ./tests/setup-k8s-tools.sh && ./tests/setup-k8s-tools.sh
  - chmod +x ./tests/create-k8s-cluster-tiller.sh && ./tests/create-k8s-cluster-tiller.sh
  - chmod +x ./tests/create-k8s-cluster-tillerless.sh && ./tests/create-k8s-cluster-tillerless.sh
after_script:
  - ./tests/delete-k8s-clusters.sh

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
jobs:
  include:
    - stage: Integration testing
      script:
      - kubectx kind-bazel-tiller && go test tests/rules/package* -v
      - kubectx kind-bazel-tillerless && go test tests/rules/release* tests/rules/push* -v
