package(default_visibility = ["//visibility:public"])

filegroup(
    name = "gpg_darwin_exec",
    srcs = [
      "gpg_darwin"
    ]
)

filegroup(
    name = "gpg_linux_exec",
    srcs = [
      "gpg_linux"
    ]
)