name: Kind
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
jobs:
  tests:
    name: Integration tests
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: 1.19
    - name: Install latest version of Kind
      run: |
        GO111MODULE=on go get sigs.k8s.io/kind
    - name: Create Kind cluster
      run: |
        PATH=$(go env GOPATH)/bin:$PATH kind create cluster --name bazel-rules
        kubectl create namespace system-chartmuseum
        helm repo add stable https://charts.helm.sh/stable
        helm repo update
        helm install chartmuseum --namespace system-chartmuseum -f tests/resources/chartmuseum/values.yaml stable/chartmuseum
    - name: Setup Bazel
      uses: abhinavsingh/setup-bazel@v3
      with:
        version: 4.1.0
    - name: Run integration tests
      run: |
        gpg --import ./tests/resources/pgp/sops_test_key.asc
        go test tests/rules/* -v
